server:
  port: 8719
  servlet:
    context-path: /
spring:
  application:
    name: seckill-test

  #mongodb
  data:
    mongodb:
      uri: mongodb://localhost:37017,localhost:47017,localhost:57017/test?slaveOk=true&replicaSet=rs0

  #redis 默认lettuce
  redis:
    host: localhost
    port: 6379
    password: 2021
    database: 1
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数，默认为 8 。使用负数表示没有限制。
        max-idle: 8 # 默认连接数最大空闲的连接数，默认为 8 。使用负数表示没有限制。
        min-idle: 0 # 默认连接池最小空闲的连接数，默认为 0 。允许设置 0 和 正数。
        max-wait: 3000 # 连接池最大阻塞等待时间，单位：毫秒。默认为 -1 ，表示不限制。
    redisson:
      # 配置单点模式
      #file: classpath:redisson.yml
      config:
        # 单节点配置
        singleServerConfig:
          # 连接空闲超时，单位：毫秒
          idleConnectionTimeout: 10000
          # 连接超时，单位：毫秒
          connectTimeout: 10000
          # 命令等待超时，单位：毫秒
          timeout: 3000
          # 命令失败重试次数,如果尝试达到 retryAttempts（命令失败重试次数） 仍然不能将命令发送至某个指定的节点时，将抛出错误。
          # 如果尝试在此限制之内发送成功，则开始启用 timeout（命令等待超时） 计时。
          retryAttempts: 3
          # 命令重试发送时间间隔，单位：毫秒
          retryInterval: 1500
          # 密码
          password: 2021
          # 单个连接最大订阅数量
          subscriptionsPerConnection: 5
          # 客户端名称
          clientName: pp
          #  # 节点地址
          address: redis://localhost:6379
          # 发布和订阅连接的最小空闲连接数
          subscriptionConnectionMinimumIdleSize: 1
          # 发布和订阅连接池大小
          subscriptionConnectionPoolSize: 50
          # 最小空闲连接数
          connectionMinimumIdleSize: 32
          # 连接池大小
          connectionPoolSize: 64
          # 数据库编号
          database: 1
          # DNS监测时间间隔，单位：毫秒
          dnsMonitoringInterval: 5000
        # 线程池数量,默认值: 当前处理核数量 * 2
        #threads: 0
        # Netty线程池数量,默认值: 当前处理核数量 * 2
        #nettyThreads: 0
        # 编码
        codec: org.redisson.codec.JsonJacksonCodec
        # 传输模式
        transportMode: "NIO"

  #集成缓存
  cache:
    type: redis
    redis:
      cache-null-values: true


  #数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:db/schema-mysql.sql
    data: classpath:db/data-mysql.sql
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    #always为始终执行初始化，embedded只初始化内存数据库（默认值）,如h2等，never为不执行初始化
    initialization-mode: always
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

#swagger api
swagger:
  base-package: com.pp.seckilltest
  base-path: /**
  contact:
    email: xxx@qq.com
    name: phf
    url: http://xxx.com
  description: Starter for swagger 2.x
  enabled: true
  license: Apache License, Version 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
  title: 测试并发
  version: 2.1.0.RELEASE

#mybatis plus自动驼峰
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

zookeeper:
  url: 127.0.0.1:2181
  mongo --host 172.17.0.4 --port 37017
